"""Provides a set of useful io functions and classes from common submodules."""

from gconfid._common.src.io_util import type_converters
from gconfid._common.src.io_util.io_util import (
    GensysInputDataset,
    GensysOutputDataset,
    StcInputTable,
    StcOutputTable,
    c_argtype_input_dataset,
    c_argtype_output_dataset,
    c_argtype_parameters,
    c_return_type,
    dest_is_file,
    dest_is_object,
    interm_to_DF,
    interm_to_PAT,
    load_input_dataset,
    pack_dataset,
    pack_parms,
    unpack_output_dataset,
    write_output_dataset,
)
from gconfid._common.src.io_util.processing import (
    add_status_by_vars,
    flag_rows_where,
    handle_arrow_string_data,
    handle_pandas_string_data,
    remove_rows_where,
    sort_dataset,
)
from gconfid._common.src.io_util.type_converters import (
    DF_from_sas_file,
    PAT_from_sas_file,
    SAS_file_to_arrowipc_file,
    SAS_file_to_feather_file,
    SAS_file_to_parquet_file,
    get_default_output_spec,
    get_OPT_split_blocks,
    set_default_output_spec,
    set_OPT_split_blocks,
)
from gconfid._common.src.io_util.type_converters import (
    DF_to_PAT as pandas_to_arrow,
)
from gconfid._common.src.io_util.type_converters import (
    PAT_to_DF as arrow_to_pandas,
)

__all__ = [
    "DF_from_sas_file",
    "GensysInputDataset",
    "GensysOutputDataset",
    "PAT_from_sas_file",
    "SAS_file_to_arrowipc_file",
    "SAS_file_to_feather_file",
    "SAS_file_to_parquet_file",
    "StcInputTable",
    "StcOutputTable",
    "add_status_by_vars",
    "arrow_to_pandas",
    "c_argtype_input_dataset",
    "c_argtype_output_dataset",
    "c_argtype_parameters",
    "c_return_type",
    "dest_is_file",
    "dest_is_object",
    "flag_rows_where",
    "get_OPT_split_blocks",
    "get_default_output_spec",
    "handle_arrow_string_data",
    "handle_pandas_string_data",
    "interm_to_DF",
    "interm_to_PAT",
    "load_input_dataset",
    "pack_dataset",
    "pack_parms",
    "pandas_to_arrow",
    "remove_rows_where",
    "set_OPT_split_blocks",
    "set_default_output_spec",
    "sort_dataset",
    "type_converters",
    "unpack_output_dataset",
    "write_output_dataset",
]
