"""Sample program which  takes a test case from G-TAB and created the Optimized Rounding inputs without using the Sensitivity module.

G-Tab has been using method 1 of GConfidRound which doesn't use a constraint file.

G-TAB tabulations have a _TYPE_ variable on them (which was generated by Proc Means), _TYPE_ is a string variable consisting of 1s and 0s to
indicate what the what grouping variables are set.
For example if a tabulations has grouping variables "SEX", "NPRCODE" and "NPRCODEG" and _TYPE_ is "101" it means that the record is broken down by SEX and NPRCODEG
but not NPRCODE. This can be used to create the constraints. _TYPE_ can easily be derived if grouping variables have all non-missing values (which they
are in G-TAB). It is also important the the unrounded solution be additive (rounds were not removed from the tabulated data before rounding). An addition
function was added to the example called check_additivity to check the unrounded and rounded totals for additivity.
"""

from pathlib import Path

import pandas as pd
from check_additivity import check_additivity

import gconfid
import gconfid.exceptions

# Load the data
test_folder = Path(__file__).resolve().parent
input_folder = test_folder / "inputdata"
incell = gconfid.io_util.DF_from_sas_file(input_folder / "unrounded.sas7bdat")

# Get a set of unique _type_ values to use create the constraints
inconstraint_bounds = incell["_TYPE_"].drop_duplicates().reset_index(drop=True)

# Create inconstraint_bounds with extra columns to note the total _type_ for each component _type_
inconstraint_bounds_total = []
inconstraint_bounds_component = []
for _TYPE_ in inconstraint_bounds:
    for i in range(len(_TYPE_)):
        if _TYPE_[i] == "1":
            total = list(_TYPE_)
            total[i] = "0"
            inconstraint_bounds_component.append(_TYPE_)
            inconstraint_bounds_total.append("".join(total))

inconstraint_bounds = pd.DataFrame()
inconstraint_bounds["component"] = inconstraint_bounds_component
inconstraint_bounds["total"] = inconstraint_bounds_total
inconstraint_bounds["ConstraintId"] = range(1, len(inconstraint_bounds) + 1)

# Create incell dataset
incell["CellId"] = range(1, len(incell) + 1)
incell["Total"] = incell["SUMWGT_GTVAR2"]
incell["Weight"] = 1
incell = incell[["YEAR", "SEX", "NPRCODE", "NPRCODEG", "CellId", "Total", "Weight","_TYPE_"]]

# Create the constraints data set
inconstraints = pd.DataFrame(columns=["ConstraintId", "CellId", "Coefficient"])

# Define a function to add constraints
def _add_constraints(row : pd.Series, inconstraint_bounds : pd.DataFrame) -> pd.DataFrame:
    components = inconstraint_bounds[inconstraint_bounds["component"] == row["_TYPE_"]]
    components = components.assign(CellId=row["CellId"], Coefficient=1)
    totals = inconstraint_bounds[inconstraint_bounds["total"] == row["_TYPE_"]]
    totals = totals.assign(CellId=row["CellId"], Coefficient=-1)
    return pd.concat([totals[["ConstraintId", "CellId", "Coefficient"]], components[["ConstraintId", "CellId", "Coefficient"]]])

for _, row in incell.iterrows():
    inconstraints = pd.concat([inconstraints, _add_constraints(row, inconstraint_bounds)])

# Sort the constraints
inconstraints = inconstraints.sort_values(by=["ConstraintId", "CellId", "Coefficient"]).reset_index(drop=True)

# Remove unnecessary columns
incell = incell[["SEX", "NPRCODE", "NPRCODEG", "CellId", "Total", "Weight"]]
inconstraint_bounds = inconstraint_bounds[["ConstraintId"]]

# Check additivity will return 0 if the Total variable is additive based on the constraints
print(check_additivity(incell, inconstraints, "Total"))  # noqa: T201 - acceptable for an example

# Call the OptRound Module
result = gconfid.OptRounding(
    incell = incell,
    additive_con = inconstraints,
    additive_bound = inconstraint_bounds,
    base = 100,
)

# Check additivity will return 0 if the Total variable is additive based on the constraints
print(check_additivity(result.outround, inconstraints, "RoundedTotal")) # noqa: T201 - acceptable for an example

# Save the results
output_folder = test_folder / "out"

if not (Path.exists(output_folder)):
    Path.mkdir(output_folder)

result.outround.to_csv(output_folder / "outround.csv", index=False)
incell.to_csv(output_folder / "incell.csv", index=False)
inconstraints.to_csv(output_folder / "add_constraints.csv", index=False)
inconstraint_bounds.to_csv(output_folder / "inconstraint_bounds.csv", index=False)
