/* 
This example takes a test case from G-TAB and created the Optimized Rounding inputs without calling Proc Sensitivity
G-Tab has been using method 1 of GConfidRound which doesn't use a constraint file. 
*/ 


/* Map a library to the input folder */
%let filePath = %sysget(SAS_EXECFILEPATH);
%let dirPath = %substr(&filePath, 1, %length(&filePath) - %length(%scan(&filePath, -1, '\')) - 1);
libname test "&dirPath.\inputdata";

/* Create the constraint bounds using the _TYPE_ column (This is generated by Proc Means in G-Tab) */
/* We keep track of which totals go with which component, so that we can build the constraints in the next step */
proc sql;
   create table inconstraint_bounds as
   select distinct _type_ from test.unrounded;
run;
data inconstraint_bounds(keep=_type_ total);
   set inconstraint_bounds;
   
   do i = 1 to length(_type_);
      if substr(_type_,i,1) = '1' then do;
         total =  _type_;
         substr(total,i,1) = "0";
         output;
      end;
   end;
   if missing(total_type_) then delete;
run; 
data inconstraint_bounds;
   set inconstraint_bounds;
   ConstraintID = _N_;
run;

/* Create the constraints */
data incell(keep=SEX NPRCODE NPRCODEG CellID Total Weight) add_constraints(keep=ConstraintID CellId Coefficient);
   set test.unrounded;
   CellId = _N_;
   Total = SUMWGT_GTVAR2;
   Weight = 1;
   output incell;

   if (0) then set inconstraint_bounds(drop=total);

   length Coefficient 8;
                        
   if (_n_ = 1) then do;
      declare hash component(dataset:"inconstraint_bounds", multidata:'yes');
      
      /* Define hash table key */
      rc = component.defineKey("_type_");
      rc = component.defineData("ConstraintID");
      rc = component.defineDone();

      declare hash hshtotal(dataset:"inconstraint_bounds(drop=_type_ rename=total=_type_)", multidata:'yes');
      rc = hshtotal.defineKey("_type_");
      rc = hshtotal.defineData("ConstraintID");
      rc = hshtotal.defineDone();
   end;

    call missing(ConstraintID);
    rc=component.find();
    do while (rc = 0);
      Coefficient = 1;
      output add_constraints; 
      rc=component.find_next();
    end;

    call missing(ConstraintID);
    rc=hshtotal.find();
    do while (rc = 0);
      Coefficient = -1;
      output add_constraints; 
      rc=hshtotal.find_next();
    end;
run;
proc sort data=add_constraints;
   by ConstraintID CellId Coefficient;
run;

/* We only need the ConstraintID on the bounds data set, the bounds will default to 0 */ 
data inconstraint_bounds;
   set inconstraint_bounds(keep=ConstraintID);
run;

/* Execute GConfidOptRound from G-Confid 1.07.003*/ 
%GConfidOptRound(
    InCells=incell,
    InConstraints=inconstraint_bounds,
    InCellConstraints=add_constraints,
    OutCells=outround,
    base=100
    );
